import Head from "next/head";
import Header from '@/components/Header'
import Footer from '@/components/Footer'
import MessageBoard from '@/components/MessageBoard'


export default function Home() {
  return (
    <>
      <Head>
        <title>ICS 221 Message Board</title>
        <meta name="description" content="Generated by Faride Tari" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
<Row className=" justify-content-center">
<Col  lg={8}>
  <Header/>
</Col>
</Row>
<Row className=" justify-content-center">
<Col  lg={8}>
  <MessageBoard/>
</Col>
</Row>
<Row className=" justify-content-center">
<Col  lg={8}>
  <Footer/>
</Col>
</Row>
</Container>
    </>
  );
}
