import React from 'react';
import Head from "next/head";
import Header from '@/components/Header';
import MessageBoardComposite from '@/components/MessageBoardComposite';
import Footer from '@/components/Footer';
import { Container, Row, Col } from 'react-bootstrap';

export default function Home() {
  return (
    <>
      <Head>
        <title>Faride Message Board</title>
        <meta name="description" content="Generated by Faride" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
   
      <Container>
        <Row className="justify-content-center">
          <Col lg={8}>
            <Header />
          </Col>
        </Row>
        <Row className="justify-content-center">
          <Col lg={8}>
            <MessageBoardComposite />
          </Col>
        </Row>
        <Row className="justify-content-center">
          <Col lg={8}>
            <Footer />
          </Col>
        </Row>
      </Container>
    </>
  );
}
